name: ci

on:
  push:
    branches:
      - "main"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout tools repo
      uses: actions/checkout@v3
      with:
        repository: hujinbo/hujinbo.github.io
        ref: hexo
        submodules: true
    - uses: actions/setup-node@v3
      with:
        node-version: '14.x'
        registry-url: 'https://registry.yarnpkg.com'
    - run: yarn install --frozen-lockfile
    - name: Run build-prod
    - run: yarn build-prod
    
    
  build-package:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: '14.x'
        registry-url: 'https://registry.yarnpkg.com'
    - run: yarn install --frozen-lockfile
    - run: yarn build
    -
      name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: dist
        path: index_min.html
  
  build-images:
    runs-on: ubuntu-latest
    needs: build-package
    steps:
      -
        name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: dist
          path: /tmp
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/blog:latest
