name: Deploy

on:
  push:
    branches:
      - "main"

jobs:
  build-package:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout tools repo
      uses: actions/checkout@v3
      with:
        repository: hujinbo/hujinbo.github.io
        ref: hexo
        submodules: true
    - uses: actions/setup-node@v3
      with:
        node-version: '14.x'
        registry-url: 'https://registry.npmjs.org'
    - name: Install pandoc
      run: |
        cd /tmp
        wget -c https://github.com/jgm/pandoc/releases/download/2.19.2/pandoc-2.19.2-1-amd64.deb
        sudo dpkg -i pandoc-2.19.2-1-amd64.deb
    - name: Install dependencies
      run: npm ci
    - name: Build package
      run: npm run build-prod
    -
      name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: site
        path: public
    - 
      name: Server酱通知
      uses: easychen/github-action-server-chan@v1.0.0
      with:
        sendkey: ${{ secrets.sendkey }}
        title: "编译成功！"
          
  build-images:
    runs-on: ubuntu-latest
    needs: build-package
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: site
          path: dist
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./docker/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/blog:latest
      - 
        name: Server酱通知
        uses: easychen/github-action-server-chan@v1.0.0
        with:
          sendkey: ${{ secrets.sendkey }}
          title: "Docker镜像打包成功！"
